cart/urls.py
from django.urls import path

from . import views


app_name = 'cart'

urlpatterns = [
    path('', views.cart_view, name='cart'),
    path('update/', views.update_cart, name='update_cart'),
    path('cart_count/', views.load_cart_count, name='cart_count'),
   
]

menu/urls.py
from django.urls import path

from . import views

app_name = 'menu'

urlpatterns = [
    path('', views.menu_list, name='menu_list'),
    path('search/', views.search, name='search'),
    path('<str:slug>/', views.menu_detail, name='menu_detail'), 
    path('<str:slug>/add/', views.add_to_cart, name='add_to_cart'), 
]

payment/urls.py
from django.urls import path

from . import views

app_name = 'payment'

urlpatterns = [
    path('check-out/', views.check_out, name='check_out'),
    path('create-payment-intent/', views.payment_intent, name='payment_intent'),
    path('webhook/', views.stripe_webhook_view, name='stripe_webhook'),
    path('update_shipping/', views.payment_update_shipping, name='update_shipping'),
]

readybox/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('menus/', include('menu.urls')),
    path('cart/', include('cart.urls')),
    path('accounts/', include('accounts.urls')),
    path('payment/', include('payment.urls')),
    path('orders/', include('orders.urls')),
    path('', views.index, name='index'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models

from menu.models import Menu, Serving
from accounts.models import User

class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    added_at = models.DateTimeField(auto_now_add=True)


class CartItem(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    session_id = models.CharField(max_length=50, blank=True, null=True)
    menu = models.ForeignKey(Menu, on_delete=models.CASCADE)
    serving = models.ForeignKey(Serving, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    added_at = models.DateTimeField(auto_now_add=True)

cart/views.py
from django.db.models import F, Sum
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect

from .models import Cart, CartItem
from .cart import Cart


def cart_view(request):
    if request.user.is_authenticated:
        user_id = request.user.id
        items = CartItem.objects.filter(user_id=user_id)
    else:
        items = CartItem.objects.filter(session_id=request.session.session_key)

    items_with_subtotal = items.annotate(sub_total=F('quantity') * F('serving__price'))
    total = items_with_subtotal.aggregate(total=Sum('sub_total'))['total']
    
    context = {'items': items_with_subtotal, 'total': total}
    return render(request, 'cart/cart.html', context)      


def update_cart(request):
    item_id = request.POST.get('item_id')
    action = request.POST.get('action')
    item = CartItem.objects.get(id=item_id)
    if request.user.is_authenticated:
        items = CartItem.objects.filter(user=request.user.id)
        if action == 'remove':
            item.quantity -= 1
            item.save()
            response = {
                'item_qty': item.quantity,
                'sub_total': item.serving.price * item.quantity,
                'deleted': 'false',
                'total': sum(item.serving.price * item.quantity for item in items),
                'items_count': sum(item.quantity for item in items),
            }
            if item.quantity <= 0:
                item.delete()
                response = {
                    'item_qty': item.quantity,
                    'sub_total': item.serving.price * item.quantity,
                    'deleted': 'true',
                    'total': sum(item.serving.price * item.quantity for item in items),
                    'items_count': sum(item.quantity for item in items),
                }

        elif action == 'add':
            item.quantity += 1
            item.save()
            response = {
                'item_qty': item.quantity,
                'sub_total': item.serving.price * item.quantity,
                'deleted': 'false',
                'total': sum(item.serving.price * item.quantity for item in items),
                'items_count': sum(item.quantity for item in items),
            }

    else:
        cart = Cart(request)
        items = CartItem.objects.filter(session_id=request.session.session_key)
        if action == 'remove':
            item.quantity -= 1
            item.save()
            cart.update_item(item, item.serving, item.quantity)
            response = {
                'item_qty': item.quantity,
                'sub_total': item.serving.price * item.quantity,
                'deleted': 'false',
                'total': sum(item.serving.price * item.quantity for item in items),
                'items_count': sum(item.quantity for item in items),
            }
            if item.quantity <= 0:
                item.delete()
                response = {
                    'item_qty': item.quantity,
                    'sub_total': item.serving.price * item.quantity,
                    'deleted': 'true',
                    'total': sum(item.serving.price * item.quantity for item in items),
                    'items_count': sum(item.quantity for item in items),
                }

        elif action == 'add':
            item.quantity += 1
            item.save()
            cart.update_item(item, item.serving, item.quantity)
            response = {
                'item_qty': item.quantity,
                'sub_total': item.serving.price * item.quantity,
                'deleted': 'false',
                'total': sum(item.serving.price * item.quantity for item in items),
                'items_count': sum(item.quantity for item in items),
            }

    return JsonResponse(response)


def load_cart_count(request):
    if request.user.is_authenticated:
        items = CartItem.objects.filter(user=request.user.id)
        items_count = sum(item.quantity for item in items)
        response = {'items_count': items_count}
    else:
        items = CartItem.objects.filter(session_id=request.session.session_key)
        items_count = sum(item.quantity for item in items)
        response = {'items_count': items_count}
        
    return JsonResponse(response)


    
    
    

templates/cart/cart.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="container-xl tw-pt-28 mt-5">
    {% if items %}
    <div>
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Items</th>
                    <th scopr="col">Portion</th>
                    <th scope="col">Price</th>
                    <th scope="col">Quantity</th>
                    <th scope="col">Subtotal</th>
                </tr>
            </thead>
            <tbody>
                {% for item in items %}
                    <tr id="item-row-{{ item.id }}">
                        <td>{{ item.menu }}</td>
                        <td>{{ item.serving.title|title }}</td>
                        <td>{{ item.serving.price }}</td>
                        <td class="qty">
                            <button class="btn btn-outline-dark remove item-btn" data-itemId="{{ item.id }}" data-action="remove">-</button>
                            <span class="d-flex align-items-center" id="item-{{item.id}}">{{ item.quantity }}</span>
                            <button class="btn btn-outline-dark add item-btn" data-itemId="{{ item.id }}" data-action="add">+</button>
                        </td>
                        <td id="subtotal-{{ item.id }}">£ {{ item.sub_total|floatformat:2 }}</td>
                    </tr>
                {% endfor %}
                <td colspan="3"></td>
                <td colspan="2" class="text-center fw-bold total">Totol: £ {{ total|floatformat:2 }}</td>
            </tbody>
        </table>
        <div class="d-flex justify-content-around">  
            <a href="{% url 'menu:menu_list' %}" class="btn btn-outline-dark" id="continue">Continue shopping</a>
            <a href="{% url 'payment:check_out' %}" class="btn btn-dark">Check out</a>        
        </div>  
    </div>
    {% else %}
    <div>
        You currently have no items in the cart. <a href="{% url 'menu:menu_list' %}">Go to shop.</a>
    </div>
    {% endif %}
</div>

<script src="{% static 'js/cart/cart.js' %}"></script>

{% endblock %}