accounts/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth.views import (
    LoginView,
    PasswordResetView, 
    PasswordResetDoneView, 
    PasswordResetConfirmView, 
    PasswordResetCompleteView
)

from . import views
from .forms import UserPasswordResetConfirmForm, UserPasswordResetForm

app_name = 'accounts'

urlpatterns = [
    # registration
    path('login/', LoginView.as_view(template_name='accounts/registration/login.html'), name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.register_view, name='register'),
    path('check_username/', views.check_username, name='check_username'),

    # password reset
    path(
        'password_reset/', 
        PasswordResetView.as_view(
            template_name='accounts/user/password_reset.html', 
            success_url=reverse_lazy('accounts:password_reset_done'),
            email_template_name='accounts/user/password_reset_email.html',
            form_class=UserPasswordResetForm
        ), name='password_reset'
    ),
    path(
        'password_reset/email_confirm/', 
        PasswordResetDoneView.as_view(
            template_name='accounts/user/password_reset_status.html'
        ), name='password_reset_done'
    ),
    path(
        'password_reset/<uidb64>/<token>/', 
        PasswordResetConfirmView.as_view(
            template_name='accounts/user/password_reset_confirm.html',
            success_url=reverse_lazy('accounts:password_reset_complete'),
            form_class=UserPasswordResetConfirmForm
        ), name='password_reset_confirm'
    ),
    path(
        'password_reset/complete/', 
        PasswordResetCompleteView.as_view(
            template_name='accounts/user/password_reset_status.html'
        ), name='password_reset_complete'
    ),

    # user profile
    path('profile/edit/', views.edit_profile, name='edit_profile'),
    
]

cart/urls.py
from django.urls import path

from . import views


app_name = 'cart'

urlpatterns = [
    path('', views.cart_view, name='cart'),
    path('update/', views.update_cart, name='update_cart'),
    path('cart_count/', views.load_cart_count, name='cart_count'),
   
]

menu/urls.py
from django.urls import path

from . import views

app_name = 'menu'

urlpatterns = [
    path('', views.menu_list, name='menu_list'),
    path('search/', views.search, name='search'),
    path('<str:slug>/', views.menu_detail, name='menu_detail'), 
    path('<str:slug>/add/', views.add_to_cart, name='add_to_cart'), 
]

orders/urls.py
from django.urls import path

from . import views

app_name = 'orders'

urlpatterns = [
    path('', views.orders_view, name='orders'),
    path('<int:pk>/', views.order_detail, name='order_detail'),
    path('orderplaced/', views.order_placed, name='order_placed'),
]

readybox/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('menus/', include('menu.urls')),
    path('cart/', include('cart.urls')),
    path('accounts/', include('accounts.urls')),
    path('payment/', include('payment.urls')),
    path('orders/', include('orders.urls')),
    path('', views.index, name='index'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% block style %} {% static 'css/output.css' %} {% endblock %}">
    <script src="https://unpkg.com/htmx.org@1.8.5"></script>
    <script src="https://cdn.jsdelivr.net/npm/sortablejs@latest/Sortable.min.js"></script>
    <title>{% block title %}ReadyBox{% endblock %}</title>
</head>
<body>
    
        {% include 'navbar.html' %}

        {% block content %}{% endblock %}
        
        {% include 'footer.html' %}

        
    <script>
        document.body.addEventListener('htmx:configRequest', function(evt) {
            evt.detail.headers['X-CSRFToken'] = '{{ csrf_token }}';
        });
        
        function getCookie(name) {
            var cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                var cookies = document.cookie.split(';');
                for (var i = 0; i < cookies.length; i++) {
                var cookie = cookies[i].trim();
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
                }
            }
            return cookieValue;
        }

        function loadCartIcon() {
            let xhr = new XMLHttpRequest();
            xhr.open('GET', '/cart/cart_count/', true);
            xhr.onload = function() {
                if (xhr.status === 200) {
                    let response = JSON.parse(xhr.responseText);
                    let icon = document.getElementById('items-count');
                    icon.textContent = response.items_count
                }
            };
            xhr.send();
        }

        function loadOnce(){
            loadCartIcon();
            window.removeEventListener('DOMContentLoaded', loadOnce)
        }

        window.addEventListener('DOMContentLoaded', loadOnce);
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <script src="https://js.stripe.com/v3/"></script>
</body>
</html>

templates/footer.html
<footer class="p-5 pb-2 container-xl">
    <div class="row">
        <div class="col-6 col-md-2 mb-3">
        <h5>Section</h5>
        <ul class="nav flex-column">
            <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Home</a></li>
            <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Features</a></li>
            <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Pricing</a></li>
            <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">FAQs</a></li>
            <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">About</a></li>
        </ul>
        </div>

        <div class="col-6 col-md-2 mb-3">
        <h5>Section</h5>
        <ul class="nav flex-column">
            <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Home</a></li>
            <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Features</a></li>
            <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Pricing</a></li>
            <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">FAQs</a></li>
            <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">About</a></li>
        </ul>
        </div>

        <div class="col-6 col-md-2 mb-3">
        <h5>Section</h5>
        <ul class="nav flex-column">
            <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Home</a></li>
            <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Features</a></li>
            <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Pricing</a></li>
            <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">FAQs</a></li>
            <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">About</a></li>
        </ul>
        </div>

        <div class="col-md-5 offset-md-1 mb-3">
        <form>
            <h5>Subscribe to our newsletter</h5>
            <p>Monthly digest of what's new and exciting from us.</p>
            <div class="d-flex flex-column flex-sm-row w-100 gap-2">
            <label for="newsletter1" class="visually-hidden">Email address</label>
            <input id="newsletter1" type="text" class="form-control" placeholder="Email address">
            <button class="btn btn-success" type="button">Subscribe</button>
            </div>
        </form>
        </div>
    </div>
    <div class="py-4 border-top">
        <p class="text-center tw-text-lime-900 tw-font-medium mb-0">&copy; 2023 Company, Inc. All rights reserved.</p>
    </div>
</footer>

templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Ready Box-Your convenient food No.1 choice{% endblock %}


{% block content %}

<div class="container-fluid d-flex" id="index-main">
    <main class="container-xl text-center d-flex flex-column flex-fill justify-content-center align-self-center">
        <h1 class="tw-text-gray-200 tw-text-7xl">Perfect Healthy Diet</h1>
        <p class="lead tw-text-gray-200 tw-text-xl tw-font-medium">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Illum laudantium reiciendis aspernatur quibusdam neque asperiores magni, nam enim accusamus labore perspiciatis deserunt nesciunt ratione adipisci omnis ullam officia praesentium consequuntur.</p>
        <p class="lead">
            <a href="#" class="btn btn-lg btn-light fw-bold border-white bg-white">Learn more</a>
        </p>
    </main>
</div>
  
  
<div class="container-xl px-4 py-5" id="custom-cards">
    <h2 class="pb-2 text-center">Fresh from the farms</h2>
    <div class="row row-cols-1 row-cols-lg-3 align-items-stretch g-4 py-5">
      <div class="col">
        <div class="card card-cover h-100 overflow-hidden text-bg-dark rounded-4 shadow-lg card-bg" style="background-image: url('../static/image/veg.jpg');">
          <div class="d-flex flex-column h-100 p-5 pb-3 text-white text-shadow-1">
            <h3 class="pt-5 mt-5 display-6 lh-1 fw-bold">Short title, long jacket</h3>
            <ul class="d-flex list-unstyled mt-auto tw-pt-20">
              <li class="me-auto">
                <img src="{% static 'image/veg.jpg' %}" alt="Bootstrap" width="32" height="32" class="rounded-circle border border-white">
              </li>
              <li class="d-flex align-items-center me-3">
                <svg class="bi me-2" width="1em" height="1em"><use xlink:href="#geo-fill"/></svg>
                <small class="tw-font-medium">Earth</small>
              </li>
              <li class="d-flex align-items-center">
                <svg class="bi me-2" width="1em" height="1em"><use xlink:href="#calendar3"/></svg>
                <small class="tw-font-medium">3d</small>
              </li>
            </ul>
          </div>
        </div>
      </div>

      <div class="col">
        <div class="card card-cover h-100 overflow-hidden text-bg-dark rounded-4 shadow-lg card-bg" style="background-image: url('../static/image/veg3.jpg');">
          <div class="d-flex flex-column h-100 p-5 pb-3 text-white text-shadow-1">
            <h3 class="pt-5 mt-5 mb-4 display-6 lh-1 fw-bold">Short title, long jacket</h3>
            <ul class="d-flex list-unstyled mt-auto tw-pt-20">
              <li class="me-auto">
                <img src="{% static 'image/veg.jpg' %}" alt="Bootstrap" width="32" height="32" class="rounded-circle border border-white">
              </li>
              <li class="d-flex align-items-center me-3">
                <svg class="bi me-2" width="1em" height="1em"><use xlink:href="#geo-fill"/></svg>
                <small class="tw-font-medium">Earth</small>
              </li>
              <li class="d-flex align-items-center">
                <svg class="bi me-2" width="1em" height="1em"><use xlink:href="#calendar3"/></svg>
                <small class="tw-font-medium">3d</small>
              </li>
            </ul>
          </div>
        </div>
      </div>

      <div class="col">
        <div class="card card-cover h-100 overflow-hidden text-bg-dark rounded-4 shadow-lg card-bg" style="background-image: url('../static/image/veg2.jpg');">
          <div class="d-flex flex-column h-100 p-5 pb-3 text-white text-shadow-1">
            <h3 class="pt-5 mt-5 mb-4 display-6 lh-1 fw-bold">Short title, long jacket</h3>
            <ul class="d-flex list-unstyled mt-auto tw-pt-20">
              <li class="me-auto">
                <img src="{% static 'image/veg.jpg' %}" alt="Bootstrap" width="32" height="32" class="rounded-circle border border-white">
              </li>
              <li class="d-flex align-items-center me-3">
                <svg class="bi me-2" width="1em" height="1em"><use xlink:href="#geo-fill"/></svg>
                <small class="tw-font-medium">Earth</small>
              </li>
              <li class="d-flex align-items-center">
                <svg class="bi me-2" width="1em" height="1em"><use xlink:href="#calendar3"/></svg>
                <small class="tw-font-medium">3d</small>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
</div>

<div class="my-5">
  <div class="p-5 text-center tw-bg-lime-100/50">
    <div class="container py-5">
      <h1 class="text-body-emphasis py-5">Full-width jumbotron</h1>
      <p class="col-lg-8 mx-auto lead">
        Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ullam animi, minima laborum eum odit repudiandae assumenda eligendi. Earum illum vero temporibus sunt! In eius quaerat ab quos saepe perferendis! Earum.
      </p>
    </div>
  </div>
</div>

{% endblock %}

templates/navbar.html
{% load static %}

<nav class="navbar fixed-top navbar-expand-lg tw-bg-lime-200 tw-h-60px" id="nav-bar">
    <div class="container-fluid">
      <a class="navbar-brand ms-3 text-center text-success fw-medium" href="{% url 'index' %}">ReadyBox</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarScroll">
        <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
          <li class="nav-item ms-3">
            <a class="nav-link fw-medium" href="{% url 'menu:menu_list' %}">Menus</a>
          </li>
          <li class="nav-item ms-3">
            <a class="nav-link fw-medium" href="#">Deals</a>
          </li>
          <li class="nav-item ms-3">
            <a class="nav-link fw-medium" href="#">Deals</a>
          </li>
        </ul>
        <form class="d-flex" role="search" method="get" action="{% url 'menu:search' %}">
          <input class="form-control me-2" type="search" name="q" value='{{request.GET.q }}' placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success me-2" type="submit">Search</button>
        </form>
        {% if request.user.is_authenticated %}
        <ul class="navbar-nav me-3 my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
          <li class="nav-item dropdown">
            <span class="nav-link dropdown-toggle" href="{% url 'menu:menu_list' %}" role="button" data-bs-toggle="dropdown" aria-expanded="false">Welcome back, {{ request.user.username }}</span>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="{% url 'accounts:edit_profile' %}">My account</a></li>
              <li><a class="dropdown-item" href="{% url 'accounts:logout' %}">Log out</a></li>
            </ul>
          </li>
        </ul>
        {% else %}
          <a class="btn btn-primary" href="{% url 'accounts:login' %}">Log in</a>
          <a class="btn btn-info ms-2" href="{% url 'accounts:register' %}">Register</a>
        {% endif %}
      </div>
      <div class="d-flex align-item-center ms-2 me-3">
        <a href="{% url 'cart:cart' %}" class="link-dark">
          <svg xmlns="http://www.w3.org/2000/svg" width="26" height="26" fill="currentColor" class="bi bi-cart4" viewBox="0 0 16 16">
            <path d="M0 2.5A.5.5 0 0 1 .5 2H2a.5.5 0 0 1 .485.379L2.89 4H14.5a.5.5 0 0 1 .485.621l-1.5 6A.5.5 0 0 1 13 11H4a.5.5 0 0 1-.485-.379L1.61 3H.5a.5.5 0 0 1-.5-.5zM3.14 5l.5 2H5V5H3.14zM6 5v2h2V5H6zm3 0v2h2V5H9zm3 0v2h1.36l.5-2H12zm1.11 3H12v2h.61l.5-2zM11 8H9v2h2V8zM8 8H6v2h2V8zM5 8H3.89l.5 2H5V8zm0 5a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0zm9-1a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0z"/>
          </svg>
          <span class="position-absolute top-40 start-90 translate-middle badge rounded-pill bg-danger" id="items-count">
            0
          </span>
        </a>
      </div>
    </div>
</nav>

templates/sidebar.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
      <meta charset="UTF-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
      <link rel="stylesheet" href="{% static 'css/style.css' %}">
      <link rel="stylesheet" href="{% block style %} {% static 'css/output.css' %} {% endblock %}">
      <script src="https://unpkg.com/htmx.org@1.8.5"></script>
      <script src="https://cdn.jsdelivr.net/npm/sortablejs@latest/Sortable.min.js"></script>
      <title>{% block title %}ReadyBox{% endblock %}</title>
  </head>
  <body>
    {% include 'navbar.html' %}

    <aside class="d-flex">
      <div class="d-flex flex-column flex-shrink-0 tw-pt-28 tw-bg-lime-200 side" style="width: 280px;">
        <ul class="nav flex-column ms-3">
          <li class="nav-item">
            <a href="{% url 'accounts:edit_profile' %}" class="nav-link active fw-medium" aria-current="page">
              <div class="ms-3">
                  <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-person-circle" viewBox="0 0 16 16">
                      <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
                      <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/>
                  </svg>
                  <span class="p-2">Profile</span>
              </div>
          </a>
          </li>
          <li>
            <a href="{% url 'orders:orders' %}" class="nav-link link-body-emphasis text-body fw-medium">
              <div class="ms-3">
                  <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-table" viewBox="0 0 16 16">
                      <path d="M0 2a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V2zm15 2h-4v3h4V4zm0 4h-4v3h4V8zm0 4h-4v3h3a1 1 0 0 0 1-1v-2zm-5 3v-3H6v3h4zm-5 0v-3H1v2a1 1 0 0 0 1 1h3zm-4-4h4V8H1v3zm0-4h4V4H1v3zm5-3v3h4V4H6zm4 4H6v3h4V8z"/>
                  </svg>
                  <span class="p-2">Orders</span>
              </div>
            </a>
          </li>
          <li>
            <a href="#" class="nav-link link-body-emphasis text-body fw-medium">
              <div class="ms-3">
                  <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-stars" viewBox="0 0 16 16">
                      <path d="M7.657 6.247c.11-.33.576-.33.686 0l.645 1.937a2.89 2.89 0 0 0 1.829 1.828l1.936.645c.33.11.33.576 0 .686l-1.937.645a2.89 2.89 0 0 0-1.828 1.829l-.645 1.936a.361.361 0 0 1-.686 0l-.645-1.937a2.89 2.89 0 0 0-1.828-1.828l-1.937-.645a.361.361 0 0 1 0-.686l1.937-.645a2.89 2.89 0 0 0 1.828-1.828l.645-1.937zM3.794 1.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387A1.734 1.734 0 0 0 4.593 5.69l-.387 1.162a.217.217 0 0 1-.412 0L3.407 5.69A1.734 1.734 0 0 0 2.31 4.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387A1.734 1.734 0 0 0 3.407 2.31l.387-1.162zM10.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732L9.1 2.137a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L10.863.1z"/>
                  </svg>
                  <span class="p-2">Wish lists</span>
              </div>
            </a>
          </li>
          <li>
            <a href="#" class="nav-link link-body-emphasis text-body fw-medium">
              <div class="ms-3">
                  <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-award" viewBox="0 0 16 16">
                      <path d="M9.669.864 8 0 6.331.864l-1.858.282-.842 1.68-1.337 1.32L2.6 6l-.306 1.854 1.337 1.32.842 1.68 1.858.282L8 12l1.669-.864 1.858-.282.842-1.68 1.337-1.32L13.4 6l.306-1.854-1.337-1.32-.842-1.68L9.669.864zm1.196 1.193.684 1.365 1.086 1.072L12.387 6l.248 1.506-1.086 1.072-.684 1.365-1.51.229L8 10.874l-1.355-.702-1.51-.229-.684-1.365-1.086-1.072L3.614 6l-.25-1.506 1.087-1.072.684-1.365 1.51-.229L8 1.126l1.356.702 1.509.229z"/>
                      <path d="M4 11.794V16l4-1 4 1v-4.206l-2.018.306L8 13.126 6.018 12.1 4 11.794z"/>
                  </svg>
                  <span class="p-2">Rewards</span>
              </div>
            </a>
          </li>
        </ul>
        <hr>
        <ul class="nav flex-column ms-3">
          <li class="nav-item">
              <a href="{% url 'accounts:logout' %}" class="nav-link link-body-emphasis text-body fw-medium">
                  <div class="ms-3">
                      <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-box-arrow-right" viewBox="0 0 16 16">
                          <path fill-rule="evenodd" d="M10 12.5a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v2a.5.5 0 0 0 1 0v-2A1.5 1.5 0 0 0 9.5 2h-8A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-2a.5.5 0 0 0-1 0v2z"/>
                          <path fill-rule="evenodd" d="M15.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 0 0-.708.708L14.293 7.5H5.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3z"/>
                      </svg>
                      <span class="p-2">Logout</span>
                  </div>
              </a>
          </li>
      </ul>
    </div>
    <div class="flex-grow-1 tw-pt-28" style="margin-left: 280px;">
        <div class="overflow-auto px-5 pb-5">
            {% block side %}
              hello
            {% endblock %}
        </div>
        {% include 'footer.html' %}
    </div>
  </aside>


    <script>
      document.body.addEventListener('htmx:configRequest', function(evt) {
          evt.detail.headers['X-CSRFToken'] = '{{ csrf_token }}';
      });
      
      function getCookie(name) {
          var cookieValue = null;
          if (document.cookie && document.cookie !== '') {
              var cookies = document.cookie.split(';');
              for (var i = 0; i < cookies.length; i++) {
              var cookie = cookies[i].trim();
              if (cookie.substring(0, name.length + 1) === (name + '=')) {
                  cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                  break;
              }
              }
          }
          return cookieValue;
      }

      function loadCartIcon() {
          let xhr = new XMLHttpRequest();
          xhr.open('GET', '/cart/cart_count/', true);
          xhr.onload = function() {
              if (xhr.status === 200) {
                  let response = JSON.parse(xhr.responseText);
                  let icon = document.getElementById('items-count');
                  icon.textContent = response.items_count
              }
          };
          xhr.send();
      }

      function loadOnce(){
          loadCartIcon();
          window.removeEventListener('DOMContentLoaded', loadOnce)
      }

      window.addEventListener('DOMContentLoaded', loadOnce);
  </script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
  <script src="https://js.stripe.com/v3/"></script>
  </body>
</html>