accounts/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth.views import (
    LoginView,
    PasswordResetView, 
    PasswordResetDoneView, 
    PasswordResetConfirmView, 
    PasswordResetCompleteView
)

from . import views
from .forms import UserPasswordResetConfirmForm, UserPasswordResetForm

app_name = 'accounts'

urlpatterns = [
    # registration
    path('login/', LoginView.as_view(template_name='accounts/registration/login.html'), name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.register_view, name='register'),
    path('check_username/', views.check_username, name='check_username'),

    # password reset
    path(
        'password_reset/', 
        PasswordResetView.as_view(
            template_name='accounts/user/password_reset.html', 
            success_url=reverse_lazy('accounts:password_reset_done'),
            email_template_name='accounts/user/password_reset_email.html',
            form_class=UserPasswordResetForm
        ), name='password_reset'
    ),
    path(
        'password_reset/email_confirm/', 
        PasswordResetDoneView.as_view(
            template_name='accounts/user/password_reset_status.html'
        ), name='password_reset_done'
    ),
    path(
        'password_reset/<uidb64>/<token>/', 
        PasswordResetConfirmView.as_view(
            template_name='accounts/user/password_reset_confirm.html',
            success_url=reverse_lazy('accounts:password_reset_complete'),
            form_class=UserPasswordResetConfirmForm
        ), name='password_reset_confirm'
    ),
    path(
        'password_reset/complete/', 
        PasswordResetCompleteView.as_view(
            template_name='accounts/user/password_reset_status.html'
        ), name='password_reset_complete'
    ),

    # user profile
    path('profile/edit/', views.edit_profile, name='edit_profile'),
    
]

cart/urls.py
from django.urls import path

from . import views


app_name = 'cart'

urlpatterns = [
    path('', views.cart_view, name='cart'),
    path('update/', views.update_cart, name='update_cart'),
    path('cart_count/', views.load_cart_count, name='cart_count'),
   
]

orders/urls.py
from django.urls import path

from . import views

app_name = 'orders'

urlpatterns = [
    path('', views.orders_view, name='orders'),
    path('<int:pk>/', views.order_detail, name='order_detail'),
    path('orderplaced/', views.order_placed, name='order_placed'),
]

readybox/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('menus/', include('menu.urls')),
    path('cart/', include('cart.urls')),
    path('accounts/', include('accounts.urls')),
    path('payment/', include('payment.urls')),
    path('orders/', include('orders.urls')),
    path('', views.index, name='index'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    # add any additional fields or methods here
    email = models.EmailField(unique=True)
    mobile = models.CharField(max_length=11, blank=True, null=True)


class ShippingAddress(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=100)
    email = models.EmailField()
    postcode = models.CharField(max_length=10)
    address1 = models.CharField(max_length=80)
    address2 = models.CharField(max_length=80, blank=True, null=True)
    town = models.CharField(max_length=80)
    contact_number = models.CharField(max_length=20)
    remarks = models.CharField(max_length=100, blank=True, null=True)

    def __str__(self):
        return f"{self.full_name}  {self.address1} {self.address2}, {self.town}   {self.contact_number}"

accounts/forms.py
from django import forms
from django.contrib.auth.forms import PasswordResetForm, SetPasswordForm, UserChangeForm, UserCreationForm, PasswordChangeForm
from django.contrib.auth.password_validation import validate_password

from .models import User


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField(label='Email', widget=forms.EmailInput(attrs={'class':'form-control', 'required':'required'}))

    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']

    def clean(self):
        cleaned_data = self.cleaned_data

        username = str(self.cleaned_data['username']).lower()
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError('This user name has been taken.')
        
        email = str(cleaned_data['email']).lower()
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError('This email has been registered.')
        
        return cleaned_data


class UserPasswordResetForm(PasswordResetForm):
    email = forms.CharField(label='Email Address', widget=forms.EmailInput(attrs={'class':'form-control'}))

    def clean_email(self):
        email = self.cleaned_data['email']
        user = User.objects.filter(email=email)
        if not user:
            raise forms.ValidationError('Sorry, this email does not match the email you registed with.')
        return email


class UserPasswordResetConfirmForm(SetPasswordForm):
    new_password1 = forms.CharField(label='New password', widget=forms.PasswordInput(attrs={'class':'form-control mb-3'}))
    new_password2 = forms.CharField(label='New password confirmation', widget=forms.PasswordInput(attrs={'class':'form-control mb-3'}))


class UserProfileEditForm(forms.ModelForm):
    old_password = forms.CharField(required=False, label='Old password', widget=forms.PasswordInput(attrs={'autocomplete': 'new-password'}))
    new_password1 = forms.CharField(required=False, label='New password', widget=forms.PasswordInput)
    new_password2 = forms.CharField(required=False, label='New password confirmation', widget=forms.PasswordInput)
    
    class Meta:
        model = User
        fields = fields = ['username', 'first_name', 'last_name', 'email', 'mobile']



    def cleaned_username(self):
        username = self.cleaned_data['username']
        if username == self.instance.username:
            # If the username has not changed, return the original username
            return username
        

    def cleaned_email(self):
        email = self.cleaned_data['email']
        if email == self.instance.email:
            # If the email has not changed, return the original email
            return email


    def clean(self):
        cleaned_data = super().clean()
        old_password = cleaned_data['old_password']
        new_password1 = cleaned_data['new_password1']
        new_password2 = cleaned_data['new_password2']
    
        #check password
        if old_password or new_password1 or new_password2:
            if not self.instance.check_password(old_password):
                # If the old password is incorrect, raise a validation error
                raise forms.ValidationError('Your old password was entered incorrectly. Please enter it again.')
            
            # Use the built-in PasswordChangeForm to validate the new passwords
            password_change_form = PasswordChangeForm(user=self.instance, data=cleaned_data)
            if not password_change_form.is_valid():
                # If the new passwords are invalid, raise a validation error
                raise forms.ValidationError(password_change_form.errors)
            
        return cleaned_data
    

accounts/views.py
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.shortcuts import render, redirect
from django.urls import reverse, reverse_lazy
from django.http import HttpResponse
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.views import PasswordResetView

from .forms import UserProfileEditForm, UserRegisterForm, UserPasswordResetForm
from .models import User
from cart.models import CartItem


def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('menu:menu_list')
    else:
        form = AuthenticationForm()
    context = {'form': form }
    return render(request, 'accounts/registration/login.html', context)
    

@login_required
def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('accounts:login')
    return render(request, 'accounts/registration/logout.html')


def register_view(request):
    session_id = request.session.session_key
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        
        if form.is_valid():
            user = form.save(commit=False)
            user.email = form.cleaned_data['email']
            user.save()

            cartItems = CartItem.objects.filter(session_id=session_id)
            cartItems.update(user=user)
            CartItem.objects.bulk_update(cartItems, ['user'])
            return redirect('accounts:login')
    else:
        form = UserRegisterForm()
    
    context = {'form': form}
    return render(request, 'accounts/registration/register.html', context)


def check_username(request):
    if request.htmx:
        user_name = request.POST.get('user_name')
        try:
            user = User.objects.filter(user_name=user_name)
            return HttpResponse('The username has been taken.')
        except:
            return HttpResponse('')


@login_required
def edit_profile(request):
    user = request.user
    form = UserProfileEditForm(request.POST or None, instance=user)
    context ={'form': form}
    if form.is_valid():
        user_update = form.save(commit=False)
        user_update.first_name = form.cleaned_data['first_name']
        user_update.last_name = form.cleaned_data['last_name']
        user_update.mobile = form.cleaned_data['mobile']
        update_session_auth_hash(request, user) 
        new_password = form.cleaned_data['new_password1']
        if new_password != '':
            user_update.set_password(form.cleaned_data['new_password1'])
        user_update.save()

        messages.success(request, 'Profile saved')
        print('changed success')
        context['message'] = 'success'
        return redirect(reverse('accounts:dashboard'))
   
    return render(request, 'accounts/user/profile.html', context)

templates/accounts/user/dashboard.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block title %}My account{% endblock %}

{% block content %}

<div class="container-fluid tw-pt-28">
    <div class="row" id="profile-nav">
    <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-body-tertiary sidebar collapse">
        <div class="position-sticky pt-3 sidebar-sticky">
        <ul class="nav flex-column">
            <li class="nav-item pt-1">
                <a href="{% url 'accounts:edit_profile' %}" class="nav-link active fw-medium" aria-current="page">
                    <div class="ms-3">
                        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-person-circle" viewBox="0 0 16 16">
                            <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
                            <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/>
                        </svg>
                        <span class="ps-1">Profile</span>
                    </div>
                </a>
            </li>
            <li class="nav-item pt-1">
                <a href="{% url 'orders:orders' %}" class="nav-link link-body-emphasis text-body fw-medium">
                    <div class="ms-3">
                        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-table" viewBox="0 0 16 16">
                            <path d="M0 2a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V2zm15 2h-4v3h4V4zm0 4h-4v3h4V8zm0 4h-4v3h3a1 1 0 0 0 1-1v-2zm-5 3v-3H6v3h4zm-5 0v-3H1v2a1 1 0 0 0 1 1h3zm-4-4h4V8H1v3zm0-4h4V4H1v3zm5-3v3h4V4H6zm4 4H6v3h4V8z"/>
                        </svg>
                        <span class="ps-1">Orders</span>
                    </div>
                </a>
            </li>
            <li class="nav-item pt-1">
                <a href="#" class="nav-link link-body-emphasis text-body fw-medium">
                    <div class="ms-3">
                        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-stars" viewBox="0 0 16 16">
                            <path d="M7.657 6.247c.11-.33.576-.33.686 0l.645 1.937a2.89 2.89 0 0 0 1.829 1.828l1.936.645c.33.11.33.576 0 .686l-1.937.645a2.89 2.89 0 0 0-1.828 1.829l-.645 1.936a.361.361 0 0 1-.686 0l-.645-1.937a2.89 2.89 0 0 0-1.828-1.828l-1.937-.645a.361.361 0 0 1 0-.686l1.937-.645a2.89 2.89 0 0 0 1.828-1.828l.645-1.937zM3.794 1.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387A1.734 1.734 0 0 0 4.593 5.69l-.387 1.162a.217.217 0 0 1-.412 0L3.407 5.69A1.734 1.734 0 0 0 2.31 4.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387A1.734 1.734 0 0 0 3.407 2.31l.387-1.162zM10.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732L9.1 2.137a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L10.863.1z"/>
                        </svg>
                        <span class="ps-1">Wish lists</span>
                    </div>
                </a>
            </li>
            <li class="nav-item pt-1">
                <a href="#" class="nav-link link-body-emphasis text-body fw-medium">
                    <div class="ms-3">
                        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-award" viewBox="0 0 16 16">
                            <path d="M9.669.864 8 0 6.331.864l-1.858.282-.842 1.68-1.337 1.32L2.6 6l-.306 1.854 1.337 1.32.842 1.68 1.858.282L8 12l1.669-.864 1.858-.282.842-1.68 1.337-1.32L13.4 6l.306-1.854-1.337-1.32-.842-1.68L9.669.864zm1.196 1.193.684 1.365 1.086 1.072L12.387 6l.248 1.506-1.086 1.072-.684 1.365-1.51.229L8 10.874l-1.355-.702-1.51-.229-.684-1.365-1.086-1.072L3.614 6l-.25-1.506 1.087-1.072.684-1.365 1.51-.229L8 1.126l1.356.702 1.509.229z"/>
                            <path d="M4 11.794V16l4-1 4 1v-4.206l-2.018.306L8 13.126 6.018 12.1 4 11.794z"/>
                        </svg>
                        <span class="ps-1">Rewards</span>
                    </div>
                </a>
            </li>
        
        </ul>

        <hr>
        <ul class="nav flex-column">
            <li class="nav-item pt-1">
                <a href="{% url 'accounts:logout' %}" class="nav-link link-body-emphasis text-body fw-medium">
                    <div class="ms-3">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-box-arrow-right" viewBox="0 0 16 16">
                            <path fill-rule="evenodd" d="M10 12.5a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v2a.5.5 0 0 0 1 0v-2A1.5 1.5 0 0 0 9.5 2h-8A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-2a.5.5 0 0 0-1 0v2z"/>
                            <path fill-rule="evenodd" d="M15.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 0 0-.708.708L14.293 7.5H5.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3z"/>
                        </svg>
                        <span class="ps-1">Logout</span>
                    </div>
                </a>
            </li>
        </ul>
        </div>
    </nav>

  <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4 h-100">
    <div class="d-flex flex-column justify-content-between flex-wrap flex-md-nowrap align-items-start ps-3 pt-3 pb-2 mb-3 border-bottom">
        <div class="container-lg">
            <form action="" method="post" class="mb-5">
                {% csrf_token %}
                <fieldset>
                    {% if messages.success %}
                        <div class="alert alert-success mt-1">
                            {{ messages.success }}
                        </div>
                    {% endif %}
                    <legend>Personal Details:</legend>
                    <label for="username" class="form-label mt-3">{{ form.username.label_tag }}</label>
                    {% render_field form.username class+='form-control mt-1' name='username' %}
                    {% if form.username.errors %}
                        <div class="alert alert-danger mt-1">
                            {{ form.username.errors }}
                        </div>
                    {% endif %}
            
                    <label for="email" class="form-label mt-3">{{ form.email.label_tag }}</label>
                    {% render_field form.email class+='form-control mt-1' name='email'%}
                    {% if form.email.errors %}
                        <div class="alert alert-danger mt-1">
                            {{ form.email.errors }}
                        </div>
                    {% endif %}
                    
                    <label for="first_name" class="form-label mt-3">{{ form.first_name.label_tag }}</label>
                    {% render_field form.first_name class+='form-control mt-1' name='first_name' placeholder='Optional' %}
                    
                    <label for="last_name" class="form-label mt-3">{{ form.last_name.label_tag }}</label>
                    {% render_field form.last_name class+='form-control mt-1' name='last_name' placeholder='Optional' %}
            
                    <label for="mobile" class="form-label mt-3">{{ form.mobile.label_tag }}</label>
                    {% render_field form.mobile class+='form-control mt-1' name='mobile' placeholder='Optional' %}
                </fieldset>
                <hr>
                <fieldset>
                    <legend>Password Details:</legend>
                    <label for="old_password" class="form-label mt-3">{{ form.old_password.label_tag }}</label>
                    {% render_field form.old_password class+='form-control mt-1' name='old_password' %}
                    {% if form.old_password.errors %}
                        <div class="alert alert-danger mt-1">
                            {{ form.old_password.errors }}
                        </div>
                    {% endif %}
            
                    <label for="new_password1" class="form-label mt-3">{{ form.new_password1.label_tag }}</label>
                    {% render_field form.new_password1 class+='form-control mt-1' name='new_password1'%}
                    {% if form.new_password1.errors %}
                        <div class="alert alert-danger mt-1">
                            {{ form.new_password1.errors }}
                        </div>
                    {% endif %}
            
                    <label for="new_password2" class="form-label mt-3">{{ form.new_password2.label_tag }}</label>
                    {% render_field form.new_password2 class+='form-control mt-1' name='new_password2'%}
                    {% if form.new_password2.errors %}
                        <div class="alert alert-danger mt-1">
                            {{ form.new_password2.errors }}
                        </div>
                    {% endif %}
                    
                </fieldset>
                <button class="btn btn-outline-primary mt-3" type="submit">Save the change</button>
                {% if messages %}
                {% for msg in messages %}
                {{ msg }}
                {% endfor %}
                {% endif %}
            </form>
            
            </div>
    </div>

    </main>

    </div>
</div>

{% endblock %}

templates/accounts/user/password_reset.html
{% extends 'base.html' %}

{% block title %}Reset Password{% endblock %}

{% block content %}

<div class="container-xl tw-pt-28">
    <div class="d-flex justify-content-center">
        <form action="{% url 'accounts:password_reset' %}" method="post" class="col-lg-8 my-2">    
            {% csrf_token %}
            <div class="pt-2">
                <label for="" class="form-label">{{ form.email.label_tag }}</label>
                {{ form.email }}
            </div>
            {% if form.errors %}
            <div class="alert alert-danger">
                {{ form.email.errors }}
            </div>
            {% endif %}
            
            <button class="btn btn-primary px-3 mt-3" type="submit">Send an email</button>
        </form>
    </div>
</div>

{% endblock %}

templates/accounts/user/password_reset_confirm.html
{% extends 'base.html' %}

{% block content %}
    <div class="content-section container-xl tw-pt-28">
        <form action="" method="post" class="my-2">
            {% csrf_token %}
            <div class="py-2">
                <label for="">{{ form.new_password1.label_tag }}</label>
                {{ form.new_password1 }}
                {% if form.new_password1.errors %}
                <div class="alert alert-danger">
                        {% for error in errors %}
                        <li>{{ error }}</li>
                        {% endfor %}
                </div>
                {% endif %}
            </div>
            
            <div class="py-2">
                <label for="">{{ form.new_password2.label_tag }}</label>
                {{ form.new_password2 }}
                {% if form.new_password2.errors %}
                <div class="alert alert-danger">
                    {% for error in errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            
            <button class="btn btn-outline-primary" type="submit">Reset Password</button>
        </form>
    </div>
{% endblock %}

templates/accounts/user/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

templates/accounts/user/password_reset_status.html
{% extends 'base.html' %}

{% block title %}Password reset sent{% endblock %}

{% block content %}
<div class="container-xl tw-pt-28">
    <div class="row no-gutter">
        <div class="col-md-12">
            <div class="login d-flex align-items-center py-5">
                <div class="container">
                    <div class="row">
                        <div class="col-12 col-lg-6">
                            <div class="p-4">
                                {% if 'email' in request.get_full_path %}
                                    <h3 class="mb-4">Password Reset Success</h3>
                                    <p>Check your email for instructions</p>
                                {% endif%}
                                {% if 'complete' in request.get_full_path %}
                                    <h3 class="mb-4">Password Reset Success</h3>
                                    <a href="{% url 'accounts:login' %}">Login</a>
                                {% endif%}
                            </div>       
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/accounts/user/profile.html
{% extends 'sidebar.html' %}
{% load widget_tweaks %}

{% block title %}My account{% endblock %}

{% block side %}
<form action="" method="post" class="my-2">
  {% csrf_token %}
  <fieldset>
      {% if messages.success %}
          <div class="alert alert-success mt-1">
              {{ messages.success }}
          </div>
      {% endif %}
      <legend>Personal Details:</legend>
      <div class="py-1">
        <label for="username" class="form-label mt-3">{{ form.username.label_tag }}</label>
      {% render_field form.username class+='form-control' name='username' %}
      {% if form.username.errors %}
          <div class="alert alert-danger mt-1">
              {{ form.username.errors }}
          </div>
      {% endif %}
      </div>

      <div class="py-1">
        <label for="email" class="form-label mt-3">{{ form.email.label_tag }}</label>
      {% render_field form.email class+='form-control' name='email'%}
      {% if form.email.errors %}
          <div class="alert alert-danger mt-1">
              {{ form.email.errors }}
          </div>
      {% endif %}
      </div>
      
      <div class="py-1">
        <label for="first_name" class="form-label mt-3">{{ form.first_name.label_tag }}</label>
      {% render_field form.first_name class+='form-control' name='first_name' placeholder='Optional' %}
      </div>
      
      <div class="py-1">
        <label for="last_name" class="form-label mt-3">{{ form.last_name.label_tag }}</label>
      {% render_field form.last_name class+='form-control' name='last_name' placeholder='Optional' %}
      </div>

      <div class="py-1">
        <label for="mobile" class="form-label mt-3">{{ form.mobile.label_tag }}</label>
        {% render_field form.mobile class+='form-control' name='mobile' placeholder='Optional' %}
      </div>
  </fieldset>
      
  <div class="tw-bg-lime-900 my-5" style="height:2px"></div>
  <fieldset>
      <legend>Password Details:</legend>
      <div class="py-1">
        <label for="old_password" class="form-label mt-3">{{ form.old_password.label_tag }}</label>
      {% render_field form.old_password class+='form-control' name='old_password'%}
      {% if form.old_password.errors %}
          <div class="alert alert-danger mt-1">
              {{ form.old_password.errors }}
          </div>
      {% endif %}
      </div>

      <div class="py-1">
        <label for="new_password1" class="form-label mt-3">{{ form.new_password1.label_tag }}</label>
      {% render_field form.new_password1 class+='form-control' name='new_password1'%}
      {% if form.new_password1.errors %}
          <div class="alert alert-danger mt-1">
              {{ form.new_password1.errors }}
          </div>
      {% endif %}
      </div>

      <div class="py-1">
        <label for="new_password2" class="form-label mt-3">{{ form.new_password2.label_tag }}</label>
      {% render_field form.new_password2 class+='form-control' name='new_password2'%}
      {% if form.new_password2.errors %}
          <div class="alert alert-danger mt-1">
              {{ form.new_password2.errors }}
          </div>
      {% endif %}
      </div>
  </fieldset>
  <button class="btn btn-success px-3 mt-3" type="submit">Save the change</button>
</form>
{% endblock %}