cart/urls.py
from django.urls import path

from . import views


app_name = 'cart'

urlpatterns = [
    path('', views.cart_view, name='cart'),
    path('update/', views.update_cart, name='update_cart'),
    path('cart_count/', views.load_cart_count, name='cart_count'),
   
]

menu/urls.py
from django.urls import path

from . import views

app_name = 'menu'

urlpatterns = [
    path('', views.menu_list, name='menu_list'),
    path('search/', views.search, name='search'),
    path('<str:slug>/', views.menu_detail, name='menu_detail'), 
    path('<str:slug>/add/', views.add_to_cart, name='add_to_cart'), 
]

orders/urls.py
from django.urls import path

from . import views

app_name = 'orders'

urlpatterns = [
    path('', views.orders_view, name='orders'),
    path('<int:pk>/', views.order_detail, name='order_detail'),
    path('orderplaced/', views.order_placed, name='order_placed'),
]

readybox/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('menus/', include('menu.urls')),
    path('cart/', include('cart.urls')),
    path('accounts/', include('accounts.urls')),
    path('payment/', include('payment.urls')),
    path('orders/', include('orders.urls')),
    path('', views.index, name='index'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/models.py
from django.db import models
from django.db.models.query import QuerySet

from accounts.models import User, ShippingAddress
from menu.models import Menu, Serving


class PaidOrderManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(payment_status=True)


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    shipping = models.OneToOneField(ShippingAddress, on_delete=models.SET_NULL, null=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    total_amount = models.CharField(max_length=100)
    order_key = models.CharField(max_length=200)
    payment_status = models.BooleanField(default=False)
    objects = models.Manager()
    valid_orders = PaidOrderManager()

    class Meta:
        ordering = ('-created', )

    def __str__(self):
        return str(self.created)
    
    def order_status(self):
        if self.payment_status:
            return 'Paid'
        else:
            return 'Not paid'
        
    def total(self):
        return float(self.total_amount) / 100
    

class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='orderitems')
    menu = models.ForeignKey(Menu, on_delete=models.CASCADE)
    serving = models.ForeignKey(Serving, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    sub_price = models.DecimalField(max_digits=5, decimal_places=2, default=0)
    added_at = models.DateTimeField(auto_now_add=True)

    
    def sub_total(self):
        return self.quantity * self.sub_price

orders/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required

from .models import Order, OrderItem
from cart.models import CartItem

# Create your views here.
@login_required
def orders_view(request):
    orders = Order.valid_orders.filter(user_id=request.user.id)
    return render(request, 'orders/my_orders.html', {'orders': orders})


@login_required
def order_detail(request, pk):
    order = Order.objects.get(pk=pk)
    order_items = OrderItem.objects.filter(order=order)
    context = {'order': order, 'order_items': order_items}
    return render(request, 'orders/order_details.html', context)


def order_placed(request):
    items = CartItem.objects.filter(user_id=request.user.id)
    items.delete()
    return render(request, 'orders/order_placed.html')

templates/orders/my_orders.html
{% extends 'sidebar.html' %}

{% block title %}My orders{% endblock %}

{% block side %}

{% if orders %}
    <ol class="list-group list-group-numbered">
        {% for order in orders %}
        <li class="list-group-item d-flex justify-content-between align-items-start">
            <div class="ms-2 me-auto">
            <div class="fw-bold"><a href="{% url 'orders:order_detail' order.pk %}" class="tw-text-lime-900">Order: {{ order }}</a></div>
            Send to: {{ order.shipping }}
            </div>
            <div class="me-2 ms-auto">
            <div class="row"><span class="badge tw-bg-lime-900 rounded-pill">{{order.order_status}}</span></div>
            
            <div class="row">Total £ {{ order.total|floatformat:2 }}</div>
            </div>
        </li>
        {% endfor %}
    </ol>
    {% else %}
    <p>You currently have no orders.</p>
{% endif %}

{% endblock %}

templates/orders/order_details.html
{% extends 'sidebar.html' %}

{% block title %}Order details{% endblock %}

{% block side %}
   
<div class="container">
    <div class="d-flex flex-column p-5 pt-3">
        <div class="border-bottom d-flex flex-row justify-content-between px-2">
            <h5>Order No.: {{ order.id }}</h5>
            <p>Order at {{ order.updated|date:"d M, Y, H:s" }}</p>
        </div>
        <div>
            {% for item in order_items %}
            <div class="row py-3 border-bottom">
                <div class="col-3">
                    <img src="{{ item.menu.image.url }}" alt="" class="img-thumbnail" width="200px" height="200px">
                </div>
                <div class="col-6 d-flex flex-column">
                    <span><a href="{% url 'menu:menu_detail' item.menu.slug %}">{{ item.menu.title }}</a></span>
                    <div class="d-flex flex-row">
                        <span class="p-1">£{{ item.serving.price}}</span>
                        <span class="p-1"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-x" viewBox="0 0 16 16">
                            <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"/>
                          </svg></span>
                        <span class="p-1">{{ item.quantity }}</span>
                    </div>
                </div>
                <div class="col-2 d-flex flex-column">
                    <button class="btn btn-success my-2">Buy again</button>
                    <button class="btn btn-outline-success">Review</button>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>


{% endblock %}

templates/orders/order_placed.html
{% extends 'base.html' %}

{% block title %}Order placed{% endblock %}


{% block content %}

<div class="container-lg tw-pt-28 mb-5">
    <div class="alert alert-success" role="alert">
        Order placed successfully.
    </div>
    
    <a href="{% url 'orders:orders' %}" class="tw-text-lime-900">View all my orders</a>
</div>

{% endblock %}